

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset Euro_2012_stats_TEAM

### Step 3. Assign it to a variable called euro12.

In [2]:
euro12 = pd.read_csv("Euro_2012_stats_TEAM.csv")
euro12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4.0,13.0,12.0,51.90%,16.00%,32.0,0.0,0.0,0.0,...,13.0,81.30%,41.0,62.0,2.0,9.0,0.0,9.0,9.0,16.0
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0,0.0,0.0,0.0,...,9.0,60.10%,53.0,73.0,8.0,7.0,0.0,11.0,11.0,19.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0,1.0,0.0,0.0,...,10.0,66.70%,25.0,38.0,8.0,4.0,0.0,7.0,7.0,15.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0,0.0,0.0,0.0,...,22.0,88.10%,43.0,45.0,6.0,5.0,0.0,11.0,11.0,16.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0,1.0,0.0,0.0,...,6.0,54.60%,36.0,51.0,5.0,6.0,0.0,11.0,11.0,19.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0,1.0,0.0,...,10.0,62.60%,63.0,49.0,12.0,4.0,0.0,15.0,15.0,17.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0,1.0,1.0,1.0,...,13.0,65.10%,67.0,48.0,12.0,9.0,1.0,12.0,12.0,20.0
7,Italy,6.0,34.0,45.0,43.00%,7.50%,110.0,2.0,0.0,0.0,...,20.0,74.10%,101.0,89.0,16.0,16.0,0.0,18.0,18.0,19.0
8,Netherlands,2.0,12.0,36.0,25.00%,4.10%,60.0,2.0,0.0,0.0,...,12.0,70.60%,35.0,30.0,3.0,5.0,0.0,7.0,7.0,15.0
9,Poland,2.0,15.0,23.0,39.40%,5.20%,48.0,0.0,0.0,0.0,...,6.0,66.70%,48.0,56.0,3.0,7.0,1.0,7.0,7.0,17.0
10,Portugal,6.0,22.0,42.0,34.30%,9.30%,82.0,6.0,0.0,0.0,...,10.0,71.50%,73.0,90.0,10.0,12.0,0.0,14.0,14.0,16.0
11,Republic of Ireland,1.0,7.0,12.0,36.80%,5.20%,28.0,0.0,0.0,0.0,...,17.0,65.40%,43.0,51.0,11.0,6.0,1.0,10.0,10.0,17.0
12,Russia,5.0,9.0,31.0,22.50%,12.50%,59.0,2.0,0.0,0.0,...,10.0,77.00%,34.0,43.0,4.0,6.0,0.0,7.0,7.0,16.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0,0.0,1.0,0.0,...,15.0,93.80%,102.0,83.0,19.0,11.0,0.0,17.0,17.0,18.0
14,Sweden,5.0,17.0,19.0,47.20%,13.80%,39.0,3.0,0.0,0.0,...,8.0,61.60%,35.0,51.0,7.0,7.0,0.0,9.0,9.0,18.0
15,Ukraine,2.0,7.0,26.0,21.20%,6.00%,38.0,0.0,0.0,0.0,...,13.0,76.50%,48.0,31.0,4.0,5.0,0.0,9.0,9.0,18.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,https://towardsdatascience.com/data-handling-u...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Filter data Remove NAN

In [3]:
euro12 = pd.read_csv("Euro_2012_stats_TEAM.csv")
euro12.dropna()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0,0.0,0.0,0.0,...,9.0,60.10%,53.0,73.0,8.0,7.0,0.0,11.0,11.0,19.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0,1.0,0.0,0.0,...,10.0,66.70%,25.0,38.0,8.0,4.0,0.0,7.0,7.0,15.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0,0.0,0.0,0.0,...,22.0,88.10%,43.0,45.0,6.0,5.0,0.0,11.0,11.0,16.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0,1.0,0.0,0.0,...,6.0,54.60%,36.0,51.0,5.0,6.0,0.0,11.0,11.0,19.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0,1.0,0.0,...,10.0,62.60%,63.0,49.0,12.0,4.0,0.0,15.0,15.0,17.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0,1.0,1.0,1.0,...,13.0,65.10%,67.0,48.0,12.0,9.0,1.0,12.0,12.0,20.0
7,Italy,6.0,34.0,45.0,43.00%,7.50%,110.0,2.0,0.0,0.0,...,20.0,74.10%,101.0,89.0,16.0,16.0,0.0,18.0,18.0,19.0
8,Netherlands,2.0,12.0,36.0,25.00%,4.10%,60.0,2.0,0.0,0.0,...,12.0,70.60%,35.0,30.0,3.0,5.0,0.0,7.0,7.0,15.0
9,Poland,2.0,15.0,23.0,39.40%,5.20%,48.0,0.0,0.0,0.0,...,6.0,66.70%,48.0,56.0,3.0,7.0,1.0,7.0,7.0,17.0
10,Portugal,6.0,22.0,42.0,34.30%,9.30%,82.0,6.0,0.0,0.0,...,10.0,71.50%,73.0,90.0,10.0,12.0,0.0,14.0,14.0,16.0
11,Republic of Ireland,1.0,7.0,12.0,36.80%,5.20%,28.0,0.0,0.0,0.0,...,17.0,65.40%,43.0,51.0,11.0,6.0,1.0,10.0,10.0,17.0
12,Russia,5.0,9.0,31.0,22.50%,12.50%,59.0,2.0,0.0,0.0,...,10.0,77.00%,34.0,43.0,4.0,6.0,0.0,7.0,7.0,16.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0,0.0,1.0,0.0,...,15.0,93.80%,102.0,83.0,19.0,11.0,0.0,17.0,17.0,18.0
14,Sweden,5.0,17.0,19.0,47.20%,13.80%,39.0,3.0,0.0,0.0,...,8.0,61.60%,35.0,51.0,7.0,7.0,0.0,9.0,9.0,18.0
15,Ukraine,2.0,7.0,26.0,21.20%,6.00%,38.0,0.0,0.0,0.0,...,13.0,76.50%,48.0,31.0,4.0,5.0,0.0,9.0,9.0,18.0

### Step 4. Select only the Goal column.

In [4]:
goals_column=euro12.columns
print('Goal column :',goals_column[1:2],'\n')
print('All goal columns:\n',goals_column,'\n')

Goal column : Index(['Goals'], dtype='object')

All goal columns:
 Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

### Step 5. How many team participated in the Euro2012?

In [5]:
euro12_team_participate=euro12[["Team"]]
print("\nTotal teams participated",len(euro12_team_participate[:16]))

Total teams participated 16

In [6]:
euro12_team_participate[:16]

                   Team
0               Croatia
1        Czech Republic
2               Denmark
3               England
4                France
5               Germany
6                Greece
7                 Italy
8           Netherlands
9                Poland
10             Portugal
11  Republic of Ireland
12               Russia
13                Spain
14               Sweden
15              Ukraine

### Step 6. What is the number of columns in the dataset?

In [7]:
print(len(euro12.columns))

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [8]:
discipline=euro12[["Team","Yellow Cards","Red Cards"]]
discipline[:16]

                   Team  Yellow Cards  Red Cards
0               Croatia           9.0        0.0
1        Czech Republic           7.0        0.0
2               Denmark           4.0        0.0
3               England           5.0        0.0
4                France           6.0        0.0
5               Germany           4.0        0.0
6                Greece           9.0        1.0
7                 Italy          16.0        0.0
8           Netherlands           5.0        0.0
9                Poland           7.0        1.0
10             Portugal          12.0        0.0
11  Republic of Ireland           6.0        1.0
12               Russia           6.0        0.0
13                Spain          11.0        0.0
14               Sweden           7.0        0.0
15              Ukraine           5.0        0.0

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [9]:
data_euro12=euro12[["Yellow Cards","Red Cards"]].dropna()
data_euro12.sort_values(by=["Red Cards"])

    Yellow Cards  Red Cards
0            9.0        0.0
1            7.0        0.0
2            4.0        0.0
3            5.0        0.0
4            6.0        0.0
5            4.0        0.0
7           16.0        0.0
8            5.0        0.0
10          12.0        0.0
12           6.0        0.0
13          11.0        0.0
14           7.0        0.0
15           5.0        0.0
6            9.0        1.0
9            7.0        1.0
11           6.0        1.0

In [10]:
data_euro12=euro12[["Yellow Cards","Red Cards"]].dropna()
data_euro12.sort_values(by=["Yellow Cards"])

    Yellow Cards  Red Cards
2            4.0        0.0
5            4.0        0.0
3            5.0        0.0
8            5.0        0.0
15           5.0        0.0
4            6.0        0.0
11           6.0        1.0
12           6.0        0.0
1            7.0        0.0
9            7.0        1.0
14           7.0        0.0
0            9.0        0.0
6            9.0        1.0
13          11.0        0.0
10          12.0        0.0
7           16.0        0.0

### Step 9. Calculate the mean Yellow Cards given per Team

In [11]:
data_euro12=euro12[["Yellow Cards","Team"]].dropna()

number_of_team =len(data_euro12["Team"])
print('Total teams =',number_of_team)

mean_yellow_cards=data_euro12["Yellow Cards"].mean()
print('Mean yellow cards =',mean_yellow_cards)

mean_yellow_cards_per_team = mean_yellow_cards/number_of_team
print('Mean yellow cards per team =',mean_yellow_cards_per_team)

Total teams = 16
Mean yellow cards = 7.4375
Mean yellow cards per team = 0.46484375

### Step 10. Filter teams that scored more than 6 goals

In [12]:
euro12_teams = euro12[["Team","Goals"]].dropna()
print(euro12_teams)
euro12_teams[euro12_teams["Goals"]>6]

                   Team  Goals
0               Croatia    4.0
1        Czech Republic    4.0
2               Denmark    4.0
3               England    5.0
4                France    3.0
5               Germany   10.0
6                Greece    5.0
7                 Italy    6.0
8           Netherlands    2.0
9                Poland    2.0
10             Portugal    6.0
11  Republic of Ireland    1.0
12               Russia    5.0
13                Spain   12.0
14               Sweden    5.0
15              Ukraine    2.0

       Team  Goals
5   Germany   10.0
13    Spain   12.0

### Step 11. Select the teams that start with G

In [13]:
euro12_teams = euro12[["Team"]].dropna()

for euro12_team in euro12_teams["Team"]:
    for start_alph_euro12 in euro12_team:
        #print(start_alph_euro12)
        if start_alph_euro12 == 'G':
            print('Teams start with G:',euro12_team)
            
euro12_teams["Team"]

Teams start with G: Germany
Teams start with G: Greece

0                                               Croatia
1                                        Czech Republic
2                                               Denmark
3                                               England
4                                                France
5                                               Germany
6                                                Greece
7                                                 Italy
8                                           Netherlands
9                                                Poland
10                                             Portugal
11                                  Republic of Ireland
12                                               Russia
13                                                Spain
14                                               Sweden
15                                              Ukraine
19    https://towardsdatascience.com/data-handling-u...
Name: Team, dtype: object

### Step 12. Select the first 7 columns

In [14]:
print(euro12.columns[:8])
euro12.iloc[:16 ,[0,1,2,3,4,5,6,7]]

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork'],
      dtype='object')

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork
0,Croatia,4.0,13.0,12.0,51.90%,16.00%,32.0,0.0
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0,0.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0,1.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0,0.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0,1.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0,1.0
7,Italy,6.0,34.0,45.0,43.00%,7.50%,110.0,2.0
8,Netherlands,2.0,12.0,36.0,25.00%,4.10%,60.0,2.0
9,Poland,2.0,15.0,23.0,39.40%,5.20%,48.0,0.0
10,Portugal,6.0,22.0,42.0,34.30%,9.30%,82.0,6.0
11,Republic of Ireland,1.0,7.0,12.0,36.80%,5.20%,28.0,0.0
12,Russia,5.0,9.0,31.0,22.50%,12.50%,59.0,2.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0,0.0
14,Sweden,5.0,17.0,19.0,47.20%,13.80%,39.0,3.0
15,Ukraine,2.0,7.0,26.0,21.20%,6.00%,38.0,0.0

### Step 13. Select all columns except the last 3.

In [15]:
euro12.iloc[:16 ,[0,1,2,3,4,5,6,7,8,9,10,11,12]]
#euro12.head(n =12)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed
0,Croatia,4.0,13.0,12.0,51.90%,16.00%,32.0,0.0,0.0,0.0,2.0,1076.0,828.0
1,Czech Republic,4.0,13.0,18.0,41.90%,12.90%,39.0,0.0,0.0,0.0,0.0,1565.0,1223.0
2,Denmark,4.0,10.0,10.0,50.00%,20.00%,27.0,1.0,0.0,0.0,3.0,1298.0,1082.0
3,England,5.0,11.0,18.0,50.00%,17.20%,40.0,0.0,0.0,0.0,3.0,1488.0,1200.0
4,France,3.0,22.0,24.0,37.90%,6.50%,65.0,1.0,0.0,0.0,0.0,2066.0,1803.0
5,Germany,10.0,32.0,32.0,47.80%,15.60%,80.0,2.0,1.0,0.0,2.0,2774.0,2427.0
6,Greece,5.0,8.0,18.0,30.70%,19.20%,32.0,1.0,1.0,1.0,0.0,1187.0,911.0
7,Italy,6.0,34.0,45.0,43.00%,7.50%,110.0,2.0,0.0,0.0,2.0,3016.0,2531.0
8,Netherlands,2.0,12.0,36.0,25.00%,4.10%,60.0,2.0,0.0,0.0,0.0,1556.0,1381.0
9,Poland,2.0,15.0,23.0,39.40%,5.20%,48.0,0.0,0.0,0.0,1.0,1059.0,852.0
10,Portugal,6.0,22.0,42.0,34.30%,9.30%,82.0,6.0,0.0,0.0,2.0,1891.0,1461.0
11,Republic of Ireland,1.0,7.0,12.0,36.80%,5.20%,28.0,0.0,0.0,0.0,1.0,851.0,606.0
12,Russia,5.0,9.0,31.0,22.50%,12.50%,59.0,2.0,0.0,0.0,1.0,1602.0,1345.0
13,Spain,12.0,42.0,33.0,55.90%,16.00%,100.0,0.0,1.0,0.0,2.0,4317.0,3820.0
14,Sweden,5.0,17.0,19.0,47.20%,13.80%,39.0,3.0,0.0,0.0,1.0,1192.0,965.0
15,Ukraine,2.0,7.0,26.0,21.20%,6.00%,38.0,0.0,0.0,0.0,2.0,1276.0,1043.0

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [16]:
shooting_accuracy=euro12.loc[[3,7,12],['Shooting Accuracy']]
shooting_accuracy

   Shooting Accuracy
3             50.00%
7             43.00%
12            22.50%

In [17]:
shooting_accuracy=euro12.loc[[3,7,12],['Team','Shooting Accuracy']]
shooting_accuracy

       Team Shooting Accuracy
3   England            50.00%
7     Italy            43.00%
12   Russia            22.50%

# Change index names

In [18]:
#shooting_accuracy.index = ["England","Italy","Russia"]
#shooting_accuracy
new_index = ["England","Italy","Russia"]
shooting_accuracy.index = new_index
shooting_accuracy
#shooting_accuracy.columns =[""]
#shooting_accuracy.reindex(new_index )

            Team Shooting Accuracy
England  England            50.00%
Italy      Italy            43.00%
Russia    Russia            22.50%

### Step 15. Use apply method on Goal Column to make a new column called Performance, using following conditions

1. If Goals are less than or equal to 2, peformance is **Below Avg**
2. If Goals are more than 2 and less than or equal to 5, peformance is **Average**
3. If Goals are more than 5 and less than or equal to 10, peformance is **Above Average**
4. If Goals are more than 10 then peformance is **Excellent**

In [78]:
#a=euro12[['Goals']]
#a.columns=[['Performance']]
#print(a)

def change_column(x):
    
    x=x[1]
    #print(x)
    #data_euro12=x[["Goals"]]
    #data_euro12.columns=[["Performance"]]
    #data_euro12=pd.Series(x,index=['Gaols'])
    data_euro12=pd.Series(x,index=['Performance']).dropna()
    #data_euro12=data_euro12.rename(columns={"Performance":"Goals"},axis=1)#.unique()#, inplace=True)
    #data_euro12=pd.DataFrame({"Performance":data_euro12})
    print(data_euro12)
    return data_euro12 

#b=change_column(euro12)
#print(b)
euro12_data = euro12.apply(change_column,axis=1)#axis 1 is used due to column opertions

euro12_data=euro12_data["Performance"].dropna()
print("\nFilter Data frame from NaN\n",euro12_data)

a = euro12_data.unique()#list of gaols columns
print("\nFilter Unique Data are=\n",a)

c=pd.Series({'performance':a})
print("\nSeries Data Frame\n ",c)

b=pd.DataFrame({'performance':a})


for columnName, columnDatas in b.iteritems(): #['Performance']:
    #print(columnName, columnDatas)
    for columnData in columnDatas:
        
        if columnData <=2:
            print("\npeformance is Below Avg, \n Goals=",columnData)
            
        elif (2<columnData and columnData <=5):
            print("\npeformance is Average,\n Goals=",columnData)
        
        elif (5<columnData and columnData <=10):
            print("\npeformance is Above Average,\n Goals=",columnData)
            
        elif columnData >10:
            print("\npeformance is Excellent,\n Goals=",columnData)
        
b

Performance    4.0
dtype: float64
Performance    4.0
dtype: float64
Performance    4.0
dtype: float64
Performance    4.0
dtype: float64
Performance    5.0
dtype: float64
Performance    3.0
dtype: float64
Performance    10.0
dtype: float64
Performance    5.0
dtype: float64
Performance    6.0
dtype: float64
Performance    2.0
dtype: float64
Performance    2.0
dtype: float64
Performance    6.0
dtype: float64
Performance    1.0
dtype: float64
Performance    5.0
dtype: float64
Performance    12.0
dtype: float64
Performance    5.0
dtype: float64
Performance    2.0
dtype: float64
Series([], dtype: float64)
Series([], dtype: float64)
Series([], dtype: float64)
Series([], dtype: float64)

Filter Data frame from NaN
 0      4.0
1      4.0
2      4.0
3      5.0
4      3.0
5     10.0
6      5.0
7      6.0
8      2.0
9      2.0
10     6.0
11     1.0
12     5.0
13    12.0
14     5.0
15     2.0
Name: Performance, dtype: float64

Filter Unique Data are=
 [ 4.  5.  3. 10.  6.  2.  1. 12.]

Series Data Frame
  performance    [4.0, 5.0, 3.0, 10.0, 6.0, 2.0, 1.0, 12.0]
dtype: object

peformance is Average,
 Goals= 4.0

peformance is Average,
 Goals= 5.0

peformance is Average,
 Goals= 3.0

peformance is Above Average,
 Goals= 10.0

peformance is Above Average,
 Goals= 6.0

peformance is Below Avg,
 Goals= 2.0

peformance is Below Avg,
 Goals= 1.0

peformance is Excellent,
 Goals= 12.0

   performance
0          4.0
1          5.0
2          3.0
3         10.0
4          6.0
5          2.0
6          1.0
7         12.0